### ISSUE TITLE
Pixels vs EMs for media queries?

### ISSUE THREAD

**Issue by whaaaley** [taffy-grid/break#2]

**Comment by jamen** [comment]
Couldn't you do it already?  Only thing related to `em` looks like `$break-max`.

**Comment by whaaaley** [comment]
`$break-max` and `break-amount`, together, set the break points for all the media queries, which is the entire output. The reason it's `em` is because if your math works out right, the output should be smaller. However, to get `min-width` and `max-width` to line up properly, I'm switching to pixels, because the extra decimals EMs would cause (by subtracting a single pixel) would be larger in the end.
